# This is a makefile that can be run using `cargo make`. See https://sagiegurari.github.io/cargo-make/ for documentation. There is a lot more functionality than what is used here, including testing multiple platforms, running benchmarks, security checks, etc.


# Clippy is a collection of lints that can be helpful to catch common mistakes.
# See: https://doc.rust-lang.org/clippy/index.html.
# Here we can add the option "--", "-Dwarnings" to the args. This elevates warnings to errors, which is useful because we, as developers, are apt to ignore warnings.
[tasks.clippy]
command = "cargo"
args = ["clippy", "--all-targets", "--workspace"]

[tasks.build]
dependencies = ["clean"]

# The option "--document-private-items" might be useful to add to args for this tutorial-style library project.
# The option "--examples" allows you to produce documentation for examples.
[tasks.doc]
# Uncomment following line to elevate warnings to errors here as well
# env = { "RUSTDOCFLAGS" = "-Dwarnings" }
command = "cargo"
args = ["doc", "--no-deps"]

# Set alias so that the default dev flow points to my-flow instead.
[tasks.default]
alias = "my-flow"

# My dev flow.
[tasks.my-flow]
dependencies = [
    "format",
    "clean",
    "clippy", 
    "build",
    "test",
    "doc"
]